detectors:
  DuplicateMethodCall:
    max_calls: 2
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    exclude:
      - Svgeez::Builder#build
      - Svgeez::Builder#initialize
      - Svgeez::Commands::Watch#process
  UtilityFunction:
    exclude:
      - Svgeez::Elements::SymbolElement#element_contents
  NestedIterators:
    max_allow_nesting: 2

exclude_paths:
  - vendor/
