inherit_from:
  - https://raw.githubusercontent.com/jgarber623/rubocop-configs/main/.rubocop.gem.yml

# Checks the length of lines in the source code.
Layout/LineLength:
  Enabled: false

# Checks if the length of a block exceeds some maximum value.
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

# Checks for long examples.
RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash

# Checks if examples contain too many `expect` calls.
RSpec/MultipleExpectations:
  Max: 2

# Checks if example groups contain too many `let` and `subject` calls.
RSpec/MultipleMemoizedHelpers:
  Max: 6
